
import requests
import random
import datetime
import json
import time

API_URL = "http://localhost:8000"
USERNAME = "example1"
PASSWORD = "password123"
EMAIL = "example1@example.com"

def get_token():
    # 1. Try to signup
    print(f"Attempting to register user '{USERNAME}'...")
    try:
        resp = requests.post(
            f"{API_URL}/auth/signup",
            json={"username": USERNAME, "email": EMAIL, "password": PASSWORD}
        )
        if resp.status_code == 201:
            print("Signup successful.")
        elif resp.status_code == 400 and "registered" in resp.text:
            print("User already exists (as expected).")
        else:
            print(f"Signup failed: {resp.status_code} - {resp.text}")
    except Exception as e:
        print(f"Connection error: {e}")
        return None

    # 2. Login
    print(f"Logging in as '{USERNAME}'...")
    try:
        resp = requests.post(
            f"{API_URL}/auth/login",
            json={"username": USERNAME, "password": PASSWORD}
        )
        if resp.status_code == 200:
            token = resp.json()["access_token"]
            print("Login successful.")
            return token
        else:
            print(f"Login failed: {resp.status_code} - {resp.text}")
            return None
    except Exception as e:
        print(f"Connection error: {e}")
        return None

def generate_workouts(count=100):
    exercises = [
        {"name": "Squat", "type": "strength", "weight_range": (80, 140), "sets": 3},
        {"name": "Bench Press", "type": "strength", "weight_range": (60, 100), "sets": 3},
        {"name": "Deadlift", "type": "strength", "weight_range": (100, 180), "sets": 1},
        {"name": "Overhead Press", "type": "strength", "weight_range": (40, 65), "sets": 3},
        {"name": "Pull Up", "type": "strength", "weight_range": (0, 20), "sets": 3},
        {"name": "Dumbbell Row", "type": "strength", "weight_range": (20, 40), "sets": 3},
        {"name": "Running", "type": "cardio", "dist_range": (3, 10), "dur_range": (20, 60)},
        {"name": "Cycling", "type": "cardio", "dist_range": (10, 30), "dur_range": (30, 90)},
    ]
    
    workouts = []
    base_date = datetime.date.today() - datetime.timedelta(days=90)
    
    for i in range(count):
        ex = random.choice(exercises)
        day_offset = random.randint(0, 90)
        date_str = (base_date + datetime.timedelta(days=day_offset)).isoformat()
        
        w = {
            "date": date_str,
            "exercise": ex["name"],
            "notes": "Generated by seed script"
        }
        
        if ex["type"] == "strength":
            w["sets"] = ex["sets"]
            w["reps"] = random.choice(["8", "10", "12", "5"])
            w["weight"] = round(random.uniform(*ex["weight_range"]), 1)
        else:
            w["distance"] = round(random.uniform(*ex["dist_range"]), 1)
            w["duration"] = round(random.uniform(*ex["dur_range"]), 1)
            
        workouts.append(w)
        
    # Sort by date
    workouts.sort(key=lambda x: x["date"])
    return workouts

def seed_data():
    token = get_token()
    if not token:
        return

    print("Generating 100 random workouts...")
    workouts = generate_workouts(100)
    
    print("Sending batch request...")
    headers = {"Authorization": f"Bearer {token}"}
    
    try:
        resp = requests.post(
            f"{API_URL}/workouts/batch",
            json=workouts,
            headers=headers
        )
        if resp.status_code == 201:
            print(f"Success! Created {len(resp.json())} workouts.")
        else:
            print(f"Failed to create workouts: {resp.status_code} - {resp.text}")
    except Exception as e:
        print(f"Error sending request: {e}")

if __name__ == "__main__":
    seed_data()
